# Generated by Django 5.2.4 on 2025-07-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(default='Hamroyev Bobir', max_length=255),
            preserve_default=False,
        ),
    ]
