# Generated by Django 5.2.4 on 2025-07-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_amount_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
