# Generated by Django 5.2.4 on 2025-07-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_amount_eur_transaction_amount_rub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_bank',
            new_name='total_rub',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_cash',
            new_name='total_uer',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_click',
            new_name='total_usd',
        ),
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_debt',
            new_name='total_uzs',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='company',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='total_terminal',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('click', 'Click'), ('cash', 'Naqd'), ('terminal', 'Terminal'), ('bank', 'Bank')], max_length=10),
        ),
    ]
