# Generated by Django 5.2.4 on 2025-07-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_rename_total_bank_dailyreport_total_rub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], default='income', max_length=10),
            preserve_default=False,
        ),
    ]
