# Generated by Django 5.2.4 on 2025-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_dailyreport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='total_rub',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_uer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='total_uzs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
