# Generated by Django 5.2.4 on 2025-07-26 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_dailyreport_total_rub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.dailyreport'),
        ),
    ]
