# Generated by Django 5.2.4 on 2025-07-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_remove_transaction_is_approved_transaction_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='eur_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='rub_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='usd_detail',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='uzs_detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
