# Generated by Django 5.2.4 on 2025-07-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_dailyreport_eur_detail_dailyreport_rub_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
