# Generated by Django 5.2.4 on 2025-07-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_user_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
