# Generated by Django 5.2.4 on 2025-07-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_dailyreport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='category',
            field=models.CharField(default="Kommunal to'lovlar", max_length=100),
            preserve_default=False,
        ),
    ]
