# Generated by Django 5.2.4 on 2025-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_dailyreport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='operator_shift',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
