# Generated by Django 5.2.4 on 2025-07-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_dailyreport_operator_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.AddField(
            model_name='transaction',
            name='click',
            field=models.CharField(blank=True, choices=[('click1', 'Nurmuxammedova'), ('click2', 'Umarov J')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(choices=[('kenjayev_jasur', 'Kenjayev Jasur'), ('abdullayev_vohid', 'Abdullayev Vohid'), ('murodov_zubaydullo', 'Murodov Zubaydullo'), ('yarashev_kamol', 'Yarashev Kamol'), ('umarov_maxsud', 'Umarov Maxsud'), ('toxtayev_farrux', "To'xtayev Farrux"), ('amonova_rushana', 'Amonova Rushana'), ('hamidova_umida', 'Hamidova Umida')], max_length=255),
        ),
    ]
