# Generated by Django 5.2.4 on 2025-07-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_user_shift_transaction_click_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
