# Generated by Django 5.2.4 on 2025-07-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_dailyreport_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('diff', 'Qoldiq')], max_length=10)),
                ('total_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('default_uzs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('default_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('default_rub', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('default_eur', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='click',
            field=models.CharField(blank=True, choices=[('click1', 'SFB'), ('click2', 'OPT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(choices=[('kenjayev_jasur', 'Kenjayev Jasur'), ('abdullayev_vohid', 'Abdullayev Vohid'), ('murodov_zubaydullo', 'Murodov Zubaydullo'), ('yarashev_kamol', 'Yarashev Kamol'), ('umarov_maxsud', 'Umarov Maxsud'), ('toxtayev_farrux', "To'xtayev Farrux"), ('amonova_rushana', 'Amonova Rushana'), ('hamidova_umida', 'Hamidova Umida'), ('other', 'Boshqa')], max_length=255),
        ),
    ]
