# Generated by Django 5.2.4 on 2025-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_stat_alter_transaction_click_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='default_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='default_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='default_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='default_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='total_eur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='total_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='total_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stat',
            name='total_uzs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
