# Generated by Django 5.2.4 on 2025-07-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_alter_stat_default_eur_alter_stat_default_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('xarajat', 'Xarajat')], max_length=10),
        ),
    ]
