# Generated by Django 5.2.4 on 2025-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_alter_dailyreport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
