# Generated by Django 5.2.4 on 2025-12-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_dailyreport_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
