# Generated by Django 5.2.4 on 2025-12-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='total_uer',
            new_name='total_eur',
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(choices=[('kenjayev_jasur', 'Kenjayev Jasur'), ('abdullayev_vohid', 'Abdullayev Vohid'), ('murodov_zubaydullo', 'Murodov Zubaydullo'), ('yarashev_kamol', 'Yarashev Kamol'), ('umarov_maxsud', 'Umarov Maxsud'), ('axmedov_ulugbek', "Axmedov Ulug'bek"), ('amonova_rushana', 'Amonova Rushana'), ('hamidova_umida', 'Hamidova Umida'), ('other', 'Boshqa')], max_length=255),
        ),
    ]
