# Generated by Django 5.2.4 on 2026-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_rename_total_uer_dailyreport_total_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(choices=[('expense', 'Chiqim'), ('xarajat', 'Xarajat')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(max_length=255),
        ),
    ]
