# Generated by Django 5.2.4 on 2026-09-07 07:32

from django.db import migrations

PERSONS_SEED = []

CATEGORIES_SEED = [
    ('chikako zavod', 'expense'),
    ('jasur un', 'expense'),
    ('ravshan $', 'expense'),
    ('almashdi', 'expense'),
    ('rasxod den', 'expense'),
    ('mssb xarajat', 'xarajat'),
    ('opt xarajat', 'xarajat'),
    ('sfb xarajat', 'xarajat'),
]


def backfill(apps, schema_editor):
    Counterparty = apps.get_model('finance', 'Counterparty')
    Category = apps.get_model('finance', 'Category')
    Transaction = apps.get_model('finance', 'Transaction')
    DailyReport = apps.get_model('finance', 'DailyReport')

    slug_to_label = dict(PERSONS_SEED)

    for label in slug_to_label.values():
        Counterparty.objects.get_or_create(name__iexact=label, defaults={'name': label})

    for slug, label in slug_to_label.items():
        Transaction.objects.filter(type='income', counterparty=slug).update(counterparty=label)

    counterparty_values = (
        Transaction.objects.filter(type='income')
        .exclude(counterparty__isnull=True)
        .exclude(counterparty='')
        .values_list('counterparty', flat=True)
        .distinct()
    )
    for value in counterparty_values:
        value = (value or '').strip()
        if value:
            Counterparty.objects.get_or_create(name__iexact=value, defaults={'name': value})

    for name, group in CATEGORIES_SEED:
        Category.objects.get_or_create(name__iexact=name, defaults={'name': name, 'group': group})

    category_values = (
        DailyReport.objects.filter(type__in=['expense', 'xarajat'])
        .exclude(category__isnull=True)
        .exclude(category='')
        .values_list('category', flat=True)
        .distinct()
    )
    for value in category_values:
        value = (value or '').strip()
        if value:
            Category.objects.get_or_create(name__iexact=value, defaults={'name': value, 'group': 'expense'})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_category_counterparty_alter_transaction_counterparty'),
    ]

    operations = [
        migrations.RunPython(backfill, noop_reverse),
    ]
