# Generated by Django 5.2.4 on 2026-09-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_seed_income_counterparties'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='group',
            field=models.CharField(choices=[('person', 'Shaxs'), ('income', 'Kirim turi')], default='person', max_length=10),
        ),
    ]
