# Generated by Django 5.2.4 on 2026-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_alter_counterparty_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('boss', 'Rahbar'), ('cashier', 'Bosh kassir'), ('operator', 'Operator')], max_length=20),
        ),
    ]
