# Generated by Django 5.2.4 on 2026-09-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0029_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim'), ('xarajat', 'Xarajat')], max_length=10),
        ),
    ]
