# Generated by Django 5.2.4 on 2025-07-22 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_click', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_terminal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_bank', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_debt', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_closed', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_reports', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
