name: Deploy Django project

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/finance
            git stash
            git pull origin main --force
            source env/bin/activate
            /var/www/finance/env/bin/pip install -r /var/www/finance/requirements.txt
            /var/www/finance/env/bin/python manage.py migrate
            sudo systemctl daemon-reload
            sudo systemctl restart finance
